#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

for family in notoserif notosans; do
  for size in 12 14 16 18; do
    name="$(echo "${family}_${size}_FONT_ID" | tr '[:lower:]' '[:upper:]')"
    echo "#define ${name} ($(
      ruby -rdigest -e "puts [
        './${family}_${size}_regular.h',
        './${family}_${size}_bold.h',
        './${family}_${size}_bolditalic.h',
        './${family}_${size}_italic.h',
      ].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)"
    ))"
  done
done

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./nunito_10_regular.h",
  "./nunito_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./nunito_12_regular.h",
  "./nunito_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NUNITO_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./nunito_14_regular.h",
  "./nunito_14_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NUNITO_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./nunito_16_regular.h",
  "./nunito_16_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define NUNITO_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./nunito_18_regular.h",
  "./nunito_18_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./nunito_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

FONT_ID_NAMES=(
  NOTOSERIF_12_FONT_ID
  NOTOSERIF_14_FONT_ID
  NOTOSERIF_16_FONT_ID
  NOTOSERIF_18_FONT_ID
  NOTOSANS_12_FONT_ID
  NOTOSANS_14_FONT_ID
  NOTOSANS_16_FONT_ID
  NOTOSANS_18_FONT_ID
  UI_10_FONT_ID
  UI_12_FONT_ID
  NUNITO_14_FONT_ID
  NUNITO_16_FONT_ID
  NUNITO_18_FONT_ID
  SMALL_FONT_ID
)

echo ""
echo "// Font ID 0 is reserved as the \"not found\" sentinel."
echo "// Guard against any hash accidentally producing 0."
for name in "${FONT_ID_NAMES[@]}"; do
  echo "static_assert(${name} != 0, \"Font ID collision with sentinel\");"
done
